version: '3'

services:
  oracle19:
    image: oracle/database:19.3.0-se2
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=contrasena
      - ORACLE_SID=ORCLCDB
      - ORACLE_EDITION=standard
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_MEM=1GB
# docker run -d --name oracle19 \
# -p 1521:1521 -p 5500:5500 \
# -e ORACLE_PWD=contrasena \
# oracle/database:19.3.0-se2
